# Generated by Django 5.2.8 on 2025-11-24 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventry',
            fields=[
                ('recno5', models.IntegerField(db_column='RECNO5')),
                ('id', models.CharField(db_column='ID', max_length=24)),
                ('tree_id', models.CharField(db_column='TREE_ID', max_length=5)),
                ('descr_1', models.CharField(db_column='DESCR_1', max_length=80)),
                ('descr_2', models.CharField(db_column='DESCR_2', max_length=80)),
                ('autoid', models.CharField(db_column='AUTOID', max_length=16, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'db_table': 'INVENTRY',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HealthDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=50, unique=True)),
                ('type', models.CharField(default='mssql', max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('host', models.CharField(max_length=255)),
                ('port', models.PositiveIntegerField(default=1433)),
                ('db_user', models.CharField(max_length=200)),
                ('api_url', models.CharField(max_length=255)),
                ('api_login', models.CharField(max_length=200)),
                ('_db_password', models.CharField(db_column='db_password', max_length=500)),
                ('_api_pass', models.CharField(db_column='api_pass', max_length=500)),
                ('is_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Health DB',
                'verbose_name_plural': 'Health DBs',
            },
        ),
    ]
